/**
 * Meals Module — high-protein, meal-prep-style weekly plans + recipe library.
 *
 * "My Meals" = a batch meal-prep board (cook breakfasts & lunches once, eat all week)
 *              + 7 daily dinners.
 * "Family"   = 7 daily dinners.
 *
 * Click any meal → recipe card with step-by-step directions (lazy-generated by Claude,
 * then cached in the plan doc), freezer ❄️ badge + storage info.
 * Push a plan's grocery list straight to the Apple Reminders "Groceries" list.
 */

import { refs, dbSet, dbDelete, uid } from "../js/db.js";
import { generateMealPlan, generateRecipeDetail, generatePrepSession } from "../js/ai.js";

const BRIDGE = "http://localhost:3333";
const GROCERY_LIST = "Groceries";   // matches Michael's Apple Reminders list

let _container = null;
let _ctx = null;
let _stateUnsub = null;
let _local = {
  view: "plan",        // "plan" | "recipes"
  audience: "me",      // "me" | "family"
  generating: false,
  grocery: null,       // string[] awaiting confirm (grocery modal open when non-null)
  pushing: false,
  card: null,          // { kind:"plan"|"recipe", id, loading } — open recipe card
  prepOpen: false,     // Sunday prep session modal open
  prepBusy: false,     // generating the prep session
  prepStep: "select",  // "select" (choose meals) | "checklist" | "grocery"
  prepSel: [],         // mids of meals chosen for this session
  dayPick: null,       // weekday name when the dinner picker is open
};

const WEEKDAYS = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const todayWeekday = () => new Date().toLocaleDateString("en-US", { weekday: "long" });

const escH = s => String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;");

const AUDIENCES = [
  { id: "me",     label: "💪 My Meals" },
  { id: "family", label: "🏡 Family" },
];

// ── Plan helpers ─────────────────────────────────────────────────
function currentPlan(plans) {
  return plans
    .filter(p => p.audience === _local.audience)
    .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0))[0] || null;
}

function latestPlan(audience) {
  return _ctx.state().mealPlans
    .filter(p => p.audience === audience)
    .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0))[0] || null;
}

// Normalize a plan-meal or saved-recipe into a self-contained dinner snapshot
function dinnerSnapshot(m, source) {
  return {
    name: m.name || "", protein: m.protein || "", calories: m.calories || "",
    freezable: !!m.freezable, source,
    ingredients: m.ingredients || [], steps: m.steps || [],
    storage: m.storage || "", prepTime: m.prepTime || "", servings: m.servings || "",
  };
}

// Dinner choices for the weekly planner: latest plan dinners (both audiences) + saved recipes
function dinnerOptions() {
  const out = [];
  (latestPlan("me")?.dinners || []).forEach(m => out.push(dinnerSnapshot(m, "My Meals")));
  (latestPlan("family")?.days || []).forEach(d => (d.meals || []).forEach(m => out.push(dinnerSnapshot(m, "Family"))));
  _ctx.state().recipes.forEach(r => out.push(dinnerSnapshot(r, "Recipe")));
  const seen = new Set();
  return out.filter(o => {
    const k = (o.name || "").toLowerCase() + "|" + o.source;
    if (!o.name || seen.has(k)) return false;
    seen.add(k); return true;
  });
}

async function setDayDinner(day, option) {
  const cur = _ctx.state().weekDinners || {};
  const days = { ...(cur.days || {}) };
  days[day] = option ? dinnerSnapshot(option, option.source || "") : null;
  await dbSet(refs.weekDinners(), { id: "weekDinners", days });
}

// Flat list of every meal across either plan shape
function allMeals(plan) {
  if (!plan) return [];
  if (plan.prep) {
    return [
      ...(plan.prep.breakfasts || []),
      ...(plan.prep.lunches || []),
      ...(plan.prep.snacks || []),
      ...(plan.dinners || []),
    ];
  }
  return (plan.days || []).flatMap(d => d.meals || []);
}

function findMeal(plan, mid) {
  return allMeals(plan).find(m => m.mid === mid) || null;
}

// Give every meal a stable id + slot label (mutates plan in place before saving)
function tagMeals(plan) {
  const tag = (arr, slot) => (arr || []).forEach(m => { m.mid = uid(); if (slot) m.slot = slot; });
  if (plan.prep) {
    tag(plan.prep.breakfasts, "Breakfast");
    tag(plan.prep.lunches, "Lunch");
    tag(plan.prep.snacks, "Snack");
    tag(plan.dinners, "Dinner");
  } else {
    (plan.days || []).forEach(d => (d.meals || []).forEach(m => { m.mid = uid(); }));
  }
}

// Dedupe ingredients (case-insensitive) across a set of meals
function dedupeIngredients(meals) {
  const seen = new Set();
  const out = [];
  meals.forEach(m => (m.ingredients || []).forEach(ing => {
    const key = String(ing).trim().toLowerCase();
    if (key && !seen.has(key)) { seen.add(key); out.push(String(ing).trim()); }
  }));
  return out;
}

function collectGroceries(plan) {
  return dedupeIngredients(allMeals(plan));
}


// ── Render ───────────────────────────────────────────────────────
function render() {
  if (!_container || !_ctx) return;
  const { mealPlans, recipes } = _ctx.state();
  const plan = currentPlan(mealPlans);
  const myRecipes = recipes.filter(r => r.audience === _local.audience);

  _container.innerHTML = `
    <div class="module-content">
      ${renderHeader()}
      ${_local.view === "plan"    ? renderPlan(plan)         : ""}
      ${_local.view === "week"    ? renderWeek()             : ""}
      ${_local.view === "recipes" ? renderRecipes(myRecipes) : ""}
      ${_local.grocery ? renderGroceryModal(_local.grocery) : ""}
      ${_local.card ? renderCard() : ""}
      ${_local.prepOpen ? renderPrepModal(plan) : ""}
      ${_local.dayPick ? renderDayPicker() : ""}
    </div>
  `;
  bindEvents();
}

function renderHeader() {
  return `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-4);gap:var(--space-2);flex-wrap:wrap">
      <div style="display:flex;gap:var(--space-2);flex-wrap:wrap">
        ${[{id:"plan",label:"📅 Plan"},{id:"week",label:"🍽️ This Week"},{id:"recipes",label:"📖 Recipes"}].map(v => `
          <button class="btn btn-sm ${_local.view===v.id?"btn-primary":"btn-secondary"}" data-view="${v.id}">${v.label}</button>
        `).join("")}
      </div>
      ${_local.view === "plan" ? `
        <div style="display:flex;gap:var(--space-2)">
          ${AUDIENCES.map(a => `
            <button class="btn btn-sm ${_local.audience===a.id?"btn-primary":"btn-secondary"}" data-aud="${a.id}">${a.label}</button>
          `).join("")}
        </div>
      ` : ""}
    </div>
  `;
}

// ── Weekly plan view ─────────────────────────────────────────────
function renderPlan(plan) {
  const genLabel = _local.generating
    ? `<span class="spinner-sm"></span> Cooking up a plan…`
    : (plan ? "✨ Regenerate week" : "✨ Generate week");

  const actions = `
    <div style="display:flex;gap:var(--space-2);flex-wrap:wrap;margin-bottom:var(--space-4)">
      <button class="btn btn-primary btn-sm" id="gen-plan" ${_local.generating?"disabled":""}>${genLabel}</button>
      ${(plan && plan.prep) ? `<button class="btn btn-secondary btn-sm" id="prep-btn" ${_local.generating?"disabled":""}>🗓️ Sunday prep session</button>` : ""}
      ${plan ? `<button class="btn btn-secondary btn-sm" id="grocery-btn" ${_local.generating?"disabled":""}>🛒 Send groceries to Reminders</button>` : ""}
    </div>
  `;

  if (!plan) {
    return `
      ${actions}
      <div class="empty-state">
        <div class="empty-state__icon">🍱</div>
        <div class="empty-state__title">No plan yet for ${_local.audience==="family"?"the family":"your meals"}</div>
        <div class="empty-state__body">${_local.audience==="family"
          ? "Generate a week of high-protein, kid-approved family dinners."
          : "Generate a batch meal-prep board — breakfasts & lunches to cook once and eat all week, plus daily dinners."}</div>
      </div>
    `;
  }

  const header = `
    <div style="font-weight:800;font-size:var(--text-lg);margin-bottom:var(--space-1)">${escH(plan.title||"This week")}</div>
    <div style="font-size:var(--text-xs);color:var(--text-tertiary);margin-bottom:var(--space-4)">Tap any meal for the full recipe · Generated ${plan.createdAt?new Date(plan.createdAt).toLocaleDateString("en-US",{month:"short",day:"numeric"}):""}</div>
  `;

  const body = plan.prep ? renderPrepBoard(plan) : renderDinnerDays(plan);
  return `${actions}${header}${body}`;
}

// "Me" prep board
function renderPrepBoard(plan) {
  const section = (title, icon, meals) => (meals && meals.length) ? `
    <div style="margin-bottom:var(--space-4)">
      <div class="section-title" style="margin-bottom:var(--space-2)">${icon} ${title}</div>
      <div class="card">${meals.map(mealRow).join("")}</div>
    </div>
  ` : "";

  return `
    ${section("Breakfast — prep ahead", "🍳", plan.prep.breakfasts)}
    ${section("Lunch — prep ahead", "🥗", plan.prep.lunches)}
    ${section("Snacks", "🍎", plan.prep.snacks)}
    ${(plan.dinners && plan.dinners.length) ? `
      <div class="section-title" style="margin-bottom:var(--space-2)">🍽️ Dinners</div>
      <div class="card">${plan.dinners.map(m => mealRow(m, m.day)).join("")}</div>
    ` : ""}
  `;
}

// "Family" day-by-day dinners
function renderDinnerDays(plan) {
  return `
    <div style="display:flex;flex-direction:column;gap:var(--space-3)">
      ${(plan.days||[]).map((d,di) => `
        <details ${di===0?"open":""}>
          <summary style="display:flex;align-items:center;gap:var(--space-2);padding:var(--space-3) var(--space-4);background:var(--bg-surface);border-radius:var(--radius-lg);cursor:pointer;list-style:none;box-shadow:var(--shadow-sm)">
            <span style="font-weight:700;flex:1">${escH(d.day||`Day ${di+1}`)}</span>
            <span style="font-size:var(--text-xs);color:var(--text-tertiary)">${(d.meals||[]).length} meal${(d.meals||[]).length===1?"":"s"}</span>
          </summary>
          <div class="card" style="margin-top:4px">${(d.meals||[]).map(mealRow).join("")}</div>
        </details>
      `).join("")}
    </div>
  `;
}

// One tappable meal row. `dayLabel` shown for dinners on the prep board.
function mealRow(m, dayLabel) {
  const macros = [m.protein?`🥩 ${escH(m.protein)}`:"", m.calories?`🔥 ${escH(m.calories)}`:""].filter(Boolean).join(" · ");
  const meta = [
    dayLabel ? `<span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">${escH(dayLabel)}</span>` : "",
    (!dayLabel && m.slot) ? `<span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">${escH(m.slot)}</span>` : "",
    m.servings ? `<span style="font-size:var(--text-xs);color:var(--text-tertiary)">makes ${escH(m.servings)}</span>` : "",
    m.freezable ? `<span style="font-size:var(--text-xs)" title="Freezer-friendly">❄️</span>` : "",
  ].filter(Boolean).join(" ");

  return `
    <div class="list-row" style="cursor:pointer;align-items:flex-start" data-open-meal="${m.mid}">
      <div style="flex:1;min-width:0">
        <div style="display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap">
          <span style="font-weight:700;font-size:var(--text-sm)">${escH(m.name||"")}</span>
          ${meta}
        </div>
        ${macros?`<div style="font-size:var(--text-xs);font-weight:600;color:var(--color-orange);margin-top:3px">${macros}</div>`:""}
        ${m.prepNote?`<div style="font-size:var(--text-xs);color:var(--text-secondary);margin-top:3px">📦 ${escH(m.prepNote)}</div>`:""}
      </div>
      <span style="color:var(--text-tertiary);flex-shrink:0">›</span>
    </div>
  `;
}

// ── Recipe card modal ────────────────────────────────────────────
function cardMeal() {
  if (!_local.card) return null;
  const { mealPlans, recipes, weekDinners } = _ctx.state();
  if (_local.card.kind === "recipe") return recipes.find(r => r.id === _local.card.id) || null;
  if (_local.card.kind === "week") return weekDinners?.days?.[_local.card.day] || null;
  return findMeal(currentPlan(mealPlans), _local.card.id);
}

function renderCard() {
  const m = cardMeal();
  if (!m) return "";
  const macros = [m.protein?`🥩 ${escH(m.protein)}`:"", m.calories?`🔥 ${escH(m.calories)}`:""].filter(Boolean).join(" · ");
  const badges = [
    m.slot ? `<span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">${escH(m.slot)}</span>` : "",
    m.freezable ? `<span class="pill" style="background:#E3F2FD;color:#1565C0">❄️ Freezer-friendly</span>` : "",
    m.servings ? `<span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">makes ${escH(m.servings)}</span>` : "",
    m.prepTime ? `<span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">⏱ ${escH(m.prepTime)}</span>` : "",
  ].filter(Boolean).join(" ");

  const hasSteps = Array.isArray(m.steps) && m.steps.length;

  return `
    <div class="modal-overlay">
      <div class="modal" style="max-width:560px">
        <div class="modal-header">
          <h2 style="font-size:var(--text-lg)">${escH(m.name||"Recipe")}</h2>
          <button class="btn btn-ghost btn-sm" id="card-close">✕</button>
        </div>
        <div class="modal-body">
          ${badges?`<div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:var(--space-2)">${badges}</div>`:""}
          ${macros?`<div style="font-size:var(--text-sm);font-weight:700;color:var(--color-orange);margin-bottom:var(--space-3)">${macros}</div>`:""}
          ${m.storage?`<div style="font-size:var(--text-sm);color:var(--text-secondary);margin-bottom:var(--space-3)">🧊 ${escH(m.storage)}</div>`:""}

          ${(m.ingredients&&m.ingredients.length)?`
            <div class="section-title" style="margin-bottom:var(--space-2)">Ingredients</div>
            <ul style="margin:0 0 var(--space-4) 0;padding-left:1.1rem;font-size:var(--text-sm);line-height:1.7">
              ${m.ingredients.map(i=>`<li>${escH(i)}</li>`).join("")}
            </ul>
          `:""}

          <div class="section-title" style="margin-bottom:var(--space-2)">Directions</div>
          ${_local.card.loading ? `
            <div style="display:flex;align-items:center;gap:var(--space-2);color:var(--text-secondary);font-size:var(--text-sm);padding:var(--space-3) 0">
              <span class="spinner-sm"></span> Writing the recipe…
            </div>
          ` : hasSteps ? `
            <ol style="margin:0;padding-left:1.2rem;font-size:var(--text-sm);line-height:1.7">
              ${m.steps.map(s=>`<li style="margin-bottom:6px">${escH(s)}</li>`).join("")}
            </ol>
          ` : `
            <div style="font-size:var(--text-sm);color:var(--text-tertiary);padding:var(--space-2) 0">No directions yet.</div>
          `}
        </div>
        <div class="modal-footer">
          ${_local.card.kind !== "recipe" ? `<button class="btn btn-secondary" id="card-save" ${(!hasSteps||_local.card.loading)?"disabled":""}>⭐ Save to recipes</button>` : ""}
          <button class="btn btn-primary" id="card-done">Done</button>
        </div>
      </div>
    </div>
  `;
}

// ── Recipe library ───────────────────────────────────────────────
function renderRecipes(recipes) {
  if (!recipes.length) {
    return `
      <div class="empty-state">
        <div class="empty-state__icon">📖</div>
        <div class="empty-state__title">No saved recipes yet</div>
        <div class="empty-state__body">Open a meal and tap ⭐ Save to recipes to keep it here.</div>
      </div>
    `;
  }
  return `
    <div class="card">
      ${recipes.sort((a,b)=>(b.savedAt||0)-(a.savedAt||0)).map(r => {
        const macros = [r.protein?`🥩 ${escH(r.protein)}`:"", r.calories?`🔥 ${escH(r.calories)}`:""].filter(Boolean).join(" · ");
        return `
          <div class="list-row" style="cursor:pointer;align-items:flex-start" data-open-recipe="${r.id}">
            <div style="flex:1;min-width:0">
              <div style="display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap">
                <span style="font-weight:700;font-size:var(--text-sm)">${escH(r.name||"")}</span>
                ${r.freezable?`<span style="font-size:var(--text-xs)" title="Freezer-friendly">❄️</span>`:""}
              </div>
              ${macros?`<div style="font-size:var(--text-xs);font-weight:600;color:var(--color-orange);margin-top:3px">${macros}</div>`:""}
            </div>
            <button class="btn btn-ghost btn-sm" data-del-recipe="${r.id}" style="flex-shrink:0;color:var(--text-tertiary)">✕</button>
          </div>
        `;
      }).join("")}
    </div>
  `;
}

// ── This Week dinner planner ─────────────────────────────────────
function renderWeek() {
  const wd = _ctx.state().weekDinners?.days || {};
  const today = todayWeekday();
  return `
    <div style="font-size:var(--text-sm);color:var(--text-secondary);margin-bottom:var(--space-3)">
      Assign a dinner to each day — today's shows on your Home screen.
    </div>
    <div class="card">
      ${WEEKDAYS.map(day => {
        const d = wd[day];
        const isToday = day === today;
        const macros = d ? [d.protein?`🥩 ${escH(d.protein)}`:"", d.calories?`🔥 ${escH(d.calories)}`:""].filter(Boolean).join(" · ") : "";
        return `
          <div class="list-row" style="align-items:center;${isToday?"background:var(--accent-light)":""}">
            <div style="width:46px;flex-shrink:0;font-weight:700;font-size:var(--text-xs);color:${isToday?"var(--accent)":"var(--text-tertiary)"}">${day.slice(0,3)}${isToday?" •":""}</div>
            <div style="flex:1;min-width:0;cursor:pointer" data-pick-day="${day}">
              ${d && d.name ? `
                <div style="font-weight:600;font-size:var(--text-sm)">${escH(d.name)} ${d.freezable?"❄️":""}</div>
                ${macros?`<div style="font-size:var(--text-xs);font-weight:600;color:var(--color-orange);margin-top:2px">${macros}</div>`:""}
              ` : `<div style="font-size:var(--text-sm);color:var(--text-tertiary)">＋ Set dinner</div>`}
            </div>
            ${d && d.name ? `<button class="btn btn-ghost btn-sm" data-clear-day="${day}" style="flex-shrink:0;color:var(--text-tertiary)">✕</button>` : ""}
          </div>
        `;
      }).join("")}
    </div>
  `;
}

function renderDayPicker() {
  const day = _local.dayPick;
  const opts = dinnerOptions();
  return `
    <div class="modal-overlay">
      <div class="modal" style="max-width:520px">
        <div class="modal-header">
          <h2 style="font-size:var(--text-lg)">${escH(day)} dinner</h2>
          <button class="btn btn-ghost btn-sm" id="pick-close">✕</button>
        </div>
        <div class="modal-body">
          ${opts.length ? `
            <div class="card">
              ${opts.map((o,i) => {
                const macros = [o.protein?`🥩 ${escH(o.protein)}`:"", o.calories?`🔥 ${escH(o.calories)}`:""].filter(Boolean).join(" · ");
                return `
                  <div class="list-row" style="cursor:pointer;align-items:flex-start" data-assign="${i}">
                    <div style="flex:1;min-width:0">
                      <div style="display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap">
                        <span style="font-weight:700;font-size:var(--text-sm)">${escH(o.name)}</span>
                        ${o.freezable?`<span style="font-size:var(--text-xs)">❄️</span>`:""}
                        <span class="pill" style="background:var(--bg-surface-2);color:var(--text-secondary)">${escH(o.source)}</span>
                      </div>
                      ${macros?`<div style="font-size:var(--text-xs);font-weight:600;color:var(--color-orange);margin-top:2px">${macros}</div>`:""}
                    </div>
                    <span style="color:var(--text-tertiary);flex-shrink:0">›</span>
                  </div>`;
              }).join("")}
            </div>
          ` : `
            <div class="empty-state">
              <div class="empty-state__icon">🍽️</div>
              <div class="empty-state__title">No dinner options yet</div>
              <div class="empty-state__body">Generate a plan or save some recipes first.</div>
            </div>
          `}
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" id="pick-clear">Clear this day</button>
          <button class="btn btn-primary" id="pick-done">Done</button>
        </div>
      </div>
    </div>
  `;
}

// ── Grocery confirm modal ────────────────────────────────────────
function renderGroceryModal(items) {
  return `
    <div class="modal-overlay">
      <div class="modal">
        <div class="modal-header">
          <h2>🛒 Grocery list → Reminders</h2>
          <button class="btn btn-ghost btn-sm" id="grocery-close">✕</button>
        </div>
        <div class="modal-body">
          <div style="font-size:var(--text-sm);color:var(--text-secondary);margin-bottom:var(--space-2)">
            ${items.length} items will be added to your Apple Reminders "${GROCERY_LIST}" list. Edit below (one per line):
          </div>
          <textarea id="grocery-text" class="input" rows="12" style="resize:vertical;font-size:var(--text-sm)">${escH(items.join("\n"))}</textarea>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" id="grocery-cancel" ${_local.pushing?"disabled":""}>Cancel</button>
          <button class="btn btn-primary" id="grocery-push" ${_local.pushing?"disabled":""}>${_local.pushing?"Adding…":"Add to Reminders"}</button>
        </div>
      </div>
    </div>
  `;
}

// ── Sunday prep session modal ────────────────────────────────────
function renderPrepModal(plan) {
  // Guard: prep sessions only apply to the "me" prep board (e.g. if audience switched while open)
  if (!plan || !plan.prep) return "";
  const busy = _local.prepBusy;
  let bodyInner, footer;

  if (busy) {
    bodyInner = `
      <div style="display:flex;align-items:center;gap:var(--space-2);color:var(--text-secondary);font-size:var(--text-sm);padding:var(--space-4) 0">
        <span class="spinner-sm"></span> Planning your prep session…
      </div>`;
    footer = `<button class="btn btn-primary" id="prep-done" disabled>Working…</button>`;
  } else if (_local.prepStep === "select") {
    bodyInner = renderPrepSelect(plan);
    const n = _local.prepSel.length;
    footer = `
      <button class="btn btn-ghost btn-sm" id="prep-close">Cancel</button>
      <button class="btn btn-ghost btn-sm" id="prep-grocery" ${n?"":"disabled"}>🛒 Groceries</button>
      <button class="btn btn-primary" id="prep-build" ${n?"":"disabled"}>Build session${n?` (${n})`:""}</button>`;
  } else if (_local.prepStep === "grocery") {
    bodyInner = renderPrepGrocery(plan);
    footer = `
      <button class="btn btn-ghost btn-sm" id="prep-grocery-back">← Back</button>
      <button class="btn btn-primary" id="prep-grocery-send">🛒 Send to Reminders</button>`;
  } else {
    bodyInner = renderPrepChecklist(plan.prepSession);
    footer = `
      <button class="btn btn-ghost btn-sm" id="prep-change">🍽️ Change meals</button>
      <button class="btn btn-ghost btn-sm" id="prep-grocery">🛒 Groceries</button>
      <button class="btn btn-ghost btn-sm" id="prep-reset">↺ Reset</button>
      <button class="btn btn-primary" id="prep-done">Done</button>`;
  }

  return `
    <div class="modal-overlay">
      <div class="modal" style="max-width:560px">
        <div class="modal-header">
          <h2 style="font-size:var(--text-lg)">🗓️ Sunday Prep Session</h2>
          <button class="btn btn-ghost btn-sm" id="prep-close">✕</button>
        </div>
        <div class="modal-body">${bodyInner}</div>
        <div class="modal-footer">${footer}</div>
      </div>
    </div>
  `;
}

// Step 1: choose which meals to batch this Sunday
function renderPrepSelect(plan) {
  const sections = [
    { label: "Breakfasts", icon: "🍳", meals: plan.prep.breakfasts || [] },
    { label: "Lunches",    icon: "🥗", meals: plan.prep.lunches || [] },
    { label: "Snacks",     icon: "🍎", meals: plan.prep.snacks || [] },
    { label: "Dinners",    icon: "🍽️", meals: plan.dinners || [] },
  ].filter(s => s.meals.length);

  return `
    <div style="font-size:var(--text-sm);color:var(--text-secondary);margin-bottom:var(--space-3)">
      Pick the meals you're batch-prepping this Sunday — the checklist is built from just these.
    </div>
    ${sections.map(sec => `
      <div class="section-title" style="margin-bottom:var(--space-1)">${sec.icon} ${sec.label}</div>
      <div class="card" style="margin-bottom:var(--space-3)">
        ${sec.meals.map(m => {
          const on = _local.prepSel.includes(m.mid);
          return `
            <label class="list-row" style="cursor:pointer;gap:var(--space-2)">
              <input type="checkbox" data-prep-sel="${m.mid}" ${on?"checked":""} style="width:18px;height:18px;cursor:pointer;accent-color:var(--color-green);flex-shrink:0">
              <span style="flex:1;font-size:var(--text-sm);font-weight:600">${escH(m.name||"")}</span>
              ${m.servings?`<span style="font-size:var(--text-xs);color:var(--text-tertiary)">makes ${escH(m.servings)}</span>`:""}
              ${m.freezable?`<span style="font-size:var(--text-xs)" title="Freezer-friendly">❄️</span>`:""}
            </label>`;
        }).join("")}
      </div>
    `).join("")}
  `;
}

// Step 2: the working checklist
function renderPrepChecklist(s) {
  const checked = s.checked || [];
  const done = checked.filter(Boolean).length;
  const total = s.tasks.length;
  return `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-3);flex-wrap:wrap;gap:var(--space-2)">
      ${s.estimatedTime?`<span style="font-size:var(--text-sm);color:var(--text-secondary)">⏱ ${escH(s.estimatedTime)}</span>`:"<span></span>"}
      <span style="font-size:var(--text-sm);font-weight:700;color:${done===total?"var(--color-green)":"var(--color-orange)"}">${done}/${total} done</span>
    </div>
    <div style="display:flex;flex-direction:column">
      ${s.tasks.map((t,i) => {
        const on = !!checked[i];
        return `
          <label class="list-row" style="cursor:pointer;align-items:flex-start;gap:var(--space-2)">
            <input type="checkbox" data-prep-idx="${i}" ${on?"checked":""} style="width:18px;height:18px;cursor:pointer;accent-color:var(--color-green);flex-shrink:0;margin-top:1px">
            <span style="font-size:var(--text-sm);${on?"text-decoration:line-through;color:var(--text-tertiary)":""}">${escH(t)}</span>
          </label>`;
      }).join("")}
    </div>
  `;
}

// Grocery list scoped to the selected meals, broken out by meal
function renderPrepGrocery(plan) {
  const meals = allMeals(plan).filter(m => _local.prepSel.includes(m.mid));
  const total = dedupeIngredients(meals).length;
  if (!meals.length) {
    return `<div style="font-size:var(--text-sm);color:var(--text-tertiary);padding:var(--space-3) 0">No meals selected.</div>`;
  }
  return `
    <div style="font-size:var(--text-sm);color:var(--text-secondary);margin-bottom:var(--space-3)">
      Groceries for your ${meals.length} prep meal${meals.length===1?"":"s"} · ${total} unique item${total===1?"":"s"} (deduped when sent).
    </div>
    ${meals.map(m => `
      <div class="section-title" style="margin-bottom:var(--space-1)">${escH(m.name||"")}${m.servings?` <span style="font-weight:400;color:var(--text-tertiary)">· makes ${escH(m.servings)}</span>`:""}</div>
      <div class="card" style="margin-bottom:var(--space-3)">
        <div style="padding:var(--space-2) var(--space-3)">
          <ul style="margin:0;padding-left:1.1rem;font-size:var(--text-sm);line-height:1.7">
            ${(m.ingredients||[]).map(i=>`<li>${escH(i)}</li>`).join("") || '<li style="color:var(--text-tertiary)">No ingredients listed</li>'}
          </ul>
        </div>
      </div>
    `).join("")}
  `;
}

// Open the Sunday prep session — show the existing checklist, or the meal picker
function openPrepSession() {
  const plan = currentPlan(_ctx.state().mealPlans);
  if (!plan || !plan.prep) return;
  _local.prepOpen = true;
  if (plan.prepSession) {
    _local.prepStep = "checklist";
  } else {
    _local.prepStep = "select";
    _local.prepSel = [];
  }
  render();
}

// Build (or rebuild) the session from the currently selected meals
async function buildPrepSession() {
  const plan = currentPlan(_ctx.state().mealPlans);
  if (!plan || !_local.prepSel.length) return;
  const meals = allMeals(plan).filter(m => _local.prepSel.includes(m.mid));
  _local.prepBusy = true; render();
  const session = await generatePrepSession(meals);
  _local.prepBusy = false;
  if (session && Array.isArray(session.tasks)) {
    plan.prepSession = {
      estimatedTime: session.estimatedTime || "",
      tasks: session.tasks,
      checked: session.tasks.map(() => false),
      mealMids: [..._local.prepSel],
      generatedAt: Date.now(),
    };
    _local.prepStep = "checklist";
    await dbSet(refs.mealPlan(plan.id), plan);
  } else {
    alert("Couldn't build the prep session — check your API key / the bridge and try again.");
  }
  render();
}

// Open the recipe card for a planned weekday dinner (lazy-generate steps if missing)
async function openWeekCard(day) {
  _local.view = "week";
  _local.card = { kind: "week", day, loading: false };
  const d = _ctx.state().weekDinners?.days?.[day];
  if (d && !(Array.isArray(d.steps) && d.steps.length)) {
    _local.card.loading = true; render();
    const detail = await generateRecipeDetail(d, _local.audience);
    if (detail && Array.isArray(detail.steps)) {
      await setDayDinner(day, {
        ...d,
        steps: detail.steps,
        ingredients: (d.ingredients && d.ingredients.length) ? d.ingredients : (detail.ingredients || []),
        storage: detail.storage || d.storage || "",
        prepTime: detail.prepTime || d.prepTime || "",
        servings: d.servings || detail.servings || "",
        freezable: d.freezable ?? detail.freezable ?? false,
      });
    }
    if (_local.card) _local.card.loading = false;
    render();
  } else {
    render();
  }
}

// ── Events ───────────────────────────────────────────────────────
function bindEvents() {
  if (!_container) return;
  const $ = id => document.getElementById(id);
  const on = (id, ev, fn) => { const el=$(id); if(el) el.addEventListener(ev,fn); };

  _container.querySelectorAll("[data-view]").forEach(b =>
    b.addEventListener("click", () => { _local.view = b.dataset.view; render(); }));
  _container.querySelectorAll("[data-aud]").forEach(b =>
    b.addEventListener("click", () => { _local.audience = b.dataset.aud; render(); }));

  // This Week dinner planner
  _container.querySelectorAll("[data-pick-day]").forEach(el =>
    el.addEventListener("click", () => { _local.dayPick = el.dataset.pickDay; render(); }));
  _container.querySelectorAll("[data-clear-day]").forEach(btn =>
    btn.addEventListener("click", async (e) => { e.stopPropagation(); await setDayDinner(btn.dataset.clearDay, null); }));
  on("pick-close", "click", () => { _local.dayPick = null; render(); });
  on("pick-done", "click", () => { _local.dayPick = null; render(); });
  on("pick-clear", "click", async () => { const d = _local.dayPick; _local.dayPick = null; render(); await setDayDinner(d, null); });
  _container.querySelectorAll("[data-assign]").forEach(row =>
    row.addEventListener("click", async () => {
      const opts = dinnerOptions();
      const opt = opts[+row.dataset.assign];
      const d = _local.dayPick;
      _local.dayPick = null; render();
      await setDayDinner(d, opt);
    }));

  // Generate a plan
  on("gen-plan", "click", async () => {
    if (_local.generating) return;
    _local.generating = true; render();
    const plan = await generateMealPlan(_local.audience);
    _local.generating = false;
    if (!plan || (!plan.days && !plan.prep)) { render(); alert("Couldn't generate a plan — check your API key / the bridge and try again."); return; }
    tagMeals(plan);
    const id = uid();
    await dbSet(refs.mealPlan(id), {
      id, audience: _local.audience, title: plan.title || "This week",
      prep: plan.prep || null, days: plan.days || null, dinners: plan.dinners || null,
      createdAt: Date.now(),
    });
    render();
  });

  // Open a meal → recipe card (lazy-generate directions if missing)
  _container.querySelectorAll("[data-open-meal]").forEach(row =>
    row.addEventListener("click", async (e) => {
      if (e.target.closest("button")) return;
      const mid = row.dataset.openMeal;
      _local.card = { kind: "plan", id: mid, loading: false };
      const plan = currentPlan(_ctx.state().mealPlans);
      const meal = findMeal(plan, mid);
      if (meal && !(Array.isArray(meal.steps) && meal.steps.length)) {
        _local.card.loading = true; render();
        const detail = await generateRecipeDetail(meal, _local.audience);
        if (detail && Array.isArray(detail.steps)) {
          Object.assign(meal, {
            steps: detail.steps,
            storage: detail.storage || meal.storage || "",
            prepTime: detail.prepTime || meal.prepTime || "",
            servings: meal.servings || detail.servings || "",
            freezable: meal.freezable ?? detail.freezable ?? false,
          });
          await dbSet(refs.mealPlan(plan.id), plan);  // persist; subscription re-renders
        }
        if (_local.card) _local.card.loading = false;
        render();
      } else {
        render();
      }
    })
  );

  on("card-close", "click", () => { _local.card = null; render(); });
  on("card-done", "click", () => { _local.card = null; render(); });
  on("card-save", "click", async () => {
    const m = cardMeal();
    if (!m) return;
    const id = uid();
    await dbSet(refs.recipe(id), {
      id, audience: _local.audience, name: m.name || "",
      protein: m.protein || "", calories: m.calories || "",
      servings: m.servings || "", prepTime: m.prepTime || "",
      freezable: !!m.freezable, storage: m.storage || "",
      ingredients: m.ingredients || [], steps: m.steps || [],
      savedAt: Date.now(),
    });
    $("card-save").textContent = "✅ Saved";
    $("card-save").disabled = true;
  });

  // Open a saved recipe card (read-only)
  _container.querySelectorAll("[data-open-recipe]").forEach(row =>
    row.addEventListener("click", (e) => {
      if (e.target.closest("button")) return;
      _local.card = { kind: "recipe", id: row.dataset.openRecipe, loading: false };
      render();
    })
  );
  _container.querySelectorAll("[data-del-recipe]").forEach(btn =>
    btn.addEventListener("click", async (e) => { e.stopPropagation(); await dbDelete(refs.recipe(btn.dataset.delRecipe)); }));

  // Sunday prep session
  on("prep-btn", "click", () => openPrepSession());
  on("prep-close", "click", () => { _local.prepOpen = false; render(); });
  on("prep-done", "click", () => { _local.prepOpen = false; render(); });
  on("prep-build", "click", () => buildPrepSession());
  on("prep-change", "click", () => {
    const plan = currentPlan(_ctx.state().mealPlans);
    _local.prepSel = [...(plan?.prepSession?.mealMids || [])];
    _local.prepStep = "select";
    render();
  });
  on("prep-grocery", "click", () => {
    // From the checklist, scope groceries to the built session's meals
    if (_local.prepStep === "checklist") {
      const plan = currentPlan(_ctx.state().mealPlans);
      _local.prepSel = [...(plan?.prepSession?.mealMids || [])];
    }
    _local.prepStep = "grocery";
    render();
  });
  on("prep-grocery-back", "click", () => {
    const plan = currentPlan(_ctx.state().mealPlans);
    _local.prepStep = plan?.prepSession ? "checklist" : "select";
    render();
  });
  on("prep-grocery-send", "click", () => {
    const plan = currentPlan(_ctx.state().mealPlans);
    const meals = allMeals(plan).filter(m => _local.prepSel.includes(m.mid));
    _local.grocery = dedupeIngredients(meals);   // opens the editable grocery confirm modal
    _local.prepOpen = false;
    render();
  });
  on("prep-reset", "click", async () => {
    const plan = currentPlan(_ctx.state().mealPlans);
    if (!plan?.prepSession) return;
    plan.prepSession.checked = plan.prepSession.tasks.map(() => false);
    render();
    await dbSet(refs.mealPlan(plan.id), plan);
  });
  // Toggle a meal in the selection (local only until Build)
  _container.querySelectorAll("[data-prep-sel]").forEach(cb =>
    cb.addEventListener("change", () => {
      const mid = cb.dataset.prepSel;
      _local.prepSel = cb.checked
        ? [...new Set([..._local.prepSel, mid])]
        : _local.prepSel.filter(x => x !== mid);
      render();
    })
  );
  // Tick off a checklist step (persisted)
  _container.querySelectorAll("[data-prep-idx]").forEach(cb =>
    cb.addEventListener("change", async () => {
      const plan = currentPlan(_ctx.state().mealPlans);
      if (!plan?.prepSession) return;
      plan.prepSession.checked[+cb.dataset.prepIdx] = cb.checked;
      render();
      await dbSet(refs.mealPlan(plan.id), plan);
    })
  );

  // Groceries → Reminders
  on("grocery-btn", "click", () => {
    const plan = currentPlan(_ctx.state().mealPlans);
    if (!plan) return;
    _local.grocery = collectGroceries(plan);
    render();
  });
  on("grocery-close", "click", () => { _local.grocery = null; render(); });
  on("grocery-cancel", "click", () => { _local.grocery = null; render(); });
  on("grocery-push", "click", async () => {
    if (_local.pushing) return;
    const items = ($("grocery-text")?.value || "").split("\n").map(s=>s.trim()).filter(Boolean);
    if (!items.length) { _local.grocery = null; render(); return; }
    _local.pushing = true; render();
    try {
      const res = await fetch(`${BRIDGE}/reminders/add-batch`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ items: items.map(title => ({ title, list: GROCERY_LIST })) }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error("batch failed");
      _local.pushing = false; _local.grocery = null; render();
      alert(`Added ${data.count} items to your "${GROCERY_LIST}" list. 🛒`);
    } catch (e) {
      _local.pushing = false; render();
      alert("Couldn't add groceries — is the bridge running?");
    }
  });
}

// ── Lifecycle ────────────────────────────────────────────────────
export async function init(container, ctx) {
  _container = container;
  _ctx = ctx;
  const { subscribe } = await import("../js/state.js");
  _stateUnsub = subscribe(() => render());
  render();

  // Hand-off from other modules (e.g. Home's "Tonight's dinner" card)
  const view = sessionStorage.getItem("meals_view");
  if (view) { sessionStorage.removeItem("meals_view"); _local.view = view; render(); }
  const day = sessionStorage.getItem("meals_open_dinner");
  if (day) { sessionStorage.removeItem("meals_open_dinner"); openWeekCard(day); }
}

export function cleanup() {
  _stateUnsub?.();
  _stateUnsub = null;
  _container = null;
  _ctx = null;
}
